obj-$(CONFIG_NUBIA_SENSORS_BACK_TMD2725)		+= ams_tmd2725.o ams_tmd2725_prox.o ams_tmd2725_als.o ams_i2c.o ams_common.o
obj-$(CONFIG_NUBIA_SENSORS_FRONT_RGB_BH1745)	+= rohm_bh1745.o
obj-$(CONFIG_NUBIA_SENSORS_FRONT_PS_STK3332)	+= stk3x3x.o
obj-$(CONFIG_NUBIA_SENSORS_HALL_DEVICE)		+= hall_device.o
obj-$(CONFIG_NUBIA_DOUBLE_SENSORS)		+= virtual_light.o virtual_proximity.o sensor_common.o
