#
# Makefile for the led driver.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_NUBIA_LED_AW8695)	+= aw8695.o
obj-$(CONFIG_NUBIA_LED_AW22XXX)	+= leds-aw22xxx.o
obj-$(CONFIG_NUBIA_LED0_AW9106)	+= aw9106-led0.o
obj-$(CONFIG_NUBIA_LED1_AW9106)	+= aw9106-led1.o
