ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_cpas/include
ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_utils
ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_io
ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_cci
ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_req_mgr
ccflags-$(CONFIG_CAMERA_TCS3707) += -Idrivers/media/platform/msm/camera/cam_smmu/

obj-$(CONFIG_CAMERA_TCS3707) += tcs3707.o
